package com.orlandocanchola.enoe;

import android.os.Parcel;
import android.os.Parcelable;

import java.lang.reflect.Array;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Map;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/*Como voy a transmitir un arraylist de objetos por medio de un bundle en cada uno de los fragments, es necesario convertir mi
objeto en un parcel, ya cuando mi parcel este en el fragment se procederá a reconvertirlo a mi objeto original

La documentación oficial tiene un ejemplo: https://developer.android.com/reference/android/os/Parcelable
 */

public class CamposProgramas implements Parcelable {

    public final static String EXTRA_POSICIÓN = "com.orlandocanchola.enoe.POSICIÓN";

    private String nombre;
    private String campoDetallado;
    private int id;

    private static CamposProgramas[] camposProgramas = new CamposProgramas[] {
            new CamposProgramas("11 Ciencias de la educación",0),
            new CamposProgramas("111 Didáctica, pedagogía y currículo",1),
            new CamposProgramas("• Ciencias en cognición y educación","111 Didáctica, pedagogía y currículo",2),
            new CamposProgramas("• Diseño curricular","111 Didáctica, pedagogía y currículo",3),
            new CamposProgramas("• Estrategias educativas","111 Didáctica, pedagogía y currículo",4),
            new CamposProgramas("• Investigación curricular","111 Didáctica, pedagogía y currículo",5),
            new CamposProgramas("• Metodología de la enseñanza","111 Didáctica, pedagogía y currículo",6),
            new CamposProgramas("112 Planeación y evaluación educativa",7),
            new CamposProgramas("• Calidad educativa","112 Planeación y evaluación educativa",8),
            new CamposProgramas("• Desarrollo educativo","112 Planeación y evaluación educativa",9),
            new CamposProgramas("• Innovación educativa","112 Planeación y evaluación educativa",10),
            new CamposProgramas("• Investigación educativa","112 Planeación y evaluación educativa",11),
            new CamposProgramas("113 Orientación y asesoría educativa",12),
            new CamposProgramas("• Asesoría escolar","113 Orientación y asesoría educativa",13),
            new CamposProgramas("• Asesoría psicopedagógica","113 Orientación y asesoría educativa",14),
            new CamposProgramas("• Intervención educativa","113 Orientación y asesoría educativa",15),
            new CamposProgramas("• Orientación educativa","113 Orientación y asesoría educativa",16),
            new CamposProgramas("114 Tecnología educativa",17),
            new CamposProgramas("• Educación digital","114 Tecnología educativa",18),
            new CamposProgramas("• Educación virtual","114 Tecnología educativa",19),
            new CamposProgramas("• Modelos de enseñanza con aplicación de nuevas tecnologías.","114 Tecnología educativa",20),
            new CamposProgramas("110 Ciencias de la educación, programas multidisciplinarios o generales",21),
            new CamposProgramas("• Ciencias de la educación","110 Ciencias de la educación, programas multidisciplinarios o generales",22),
            new CamposProgramas("• Educación","110 Ciencias de la educación, programas multidisciplinarios o generales",23),
            new CamposProgramas("12 Formación docente",24),
            new CamposProgramas("121 Formación docente para educación básica, nivel preescolar",25),
            new CamposProgramas("• Actividades didácticas para preescolares","121 Formación docente para educación básica, nivel preescolar",26),
            new CamposProgramas("• Adquisición y desenvolvimiento del lenguaje en el niño","121 Formación docente para educación básica, nivel preescolar",27),
            new CamposProgramas("• Contenidos de la educación preescolar","121 Formación docente para educación básica, nivel preescolar",28),
            new CamposProgramas("• Educación preescolar indígena","121 Formación docente para educación básica, nivel preescolar",29),
            new CamposProgramas("• Educación preescolar intercultural","121 Formación docente para educación básica, nivel preescolar",30),
            new CamposProgramas("122 Formación docente para educación básica, nivel primaria",31),
            new CamposProgramas("• Ciencias y su enseñanza en primaria","122 Formación docente para educación básica, nivel primaria",32),
            new CamposProgramas("• Contenidos de la educación primaria","122 Formación docente para educación básica, nivel primaria",33),
            new CamposProgramas("• Educación primaria indígena","122 Formación docente para educación básica, nivel primaria",34),
            new CamposProgramas("• Educación primaria intercultural","122 Formación docente para educación básica, nivel primaria",35),
            new CamposProgramas("• Educación primaria rural","122 Formación docente para educación básica, nivel primaria",36),
            new CamposProgramas("123 Formación docente para educación básica, nivel secundaria",37),
            new CamposProgramas("• Educación para telesecundaria","123 Formación docente para educación básica, nivel secundaria",38),
            new CamposProgramas("• Educación secundaria en ciencias naturales","123 Formación docente para educación básica, nivel secundaria",39),
            new CamposProgramas("• Educación secundaria en español","123 Formación docente para educación básica, nivel secundaria",40),
            new CamposProgramas("• Educación secundaria en lenguas extranjeras","123 Formación docente para educación básica, nivel secundaria",41),
            new CamposProgramas("124 Formación docente para educación de nivel medio superior",42),
            new CamposProgramas("• Educación media superior en historia","124 Formación docente para educación de nivel medio superior",43),
            new CamposProgramas("• Educación media superior en línea","124 Formación docente para educación de nivel medio superior",44),
            new CamposProgramas("• Educación media superior en matemáticas","124 Formación docente para educación de nivel medio superior",45),
            new CamposProgramas("• Educación para telebachillerato","124 Formación docente para educación de nivel medio superior",46),
            new CamposProgramas("125 Formación docente para educación de nivel superior",47),
            new CamposProgramas("• Docencia biomédica","125 Formación docente para educación de nivel superior",48),
            new CamposProgramas("• Docencia jurídica","125 Formación docente para educación de nivel superior",49),
            new CamposProgramas("• Docencia universitaria","125 Formación docente para educación de nivel superior",50),
            new CamposProgramas("• Enseñanza superior en lengua y literatura","125 Formación docente para educación de nivel superior",51),
            new CamposProgramas("• Enseñanza superior en matemática educativa","125 Formación docente para educación de nivel superior",52),
            new CamposProgramas("• Enseñanza universitaria","125 Formación docente para educación de nivel superior",53),
            new CamposProgramas("126 Formación docente para educación física, artística o tecnológica",54),
            new CamposProgramas("• Docencia de la cultura física","126 Formación docente para educación física, artística o tecnológica",55),
            new CamposProgramas("• Docencia del arte escénico","126 Formación docente para educación física, artística o tecnológica",56),
            new CamposProgramas("• Docencia musical","126 Formación docente para educación física, artística o tecnológica",57),
            new CamposProgramas("• Docencia tecnológica","126 Formación docente para educación física, artística o tecnológica",58),
            new CamposProgramas("• Enseñanza de la danza","126 Formación docente para educación física, artística o tecnológica",59),
            new CamposProgramas("127 Formación docente para la enseñanza de asignaturas específicas",60),
            new CamposProgramas("• Enseñanza de idiomas","127 Formación docente para la enseñanza de asignaturas específicas",61),
            new CamposProgramas("• Enseñanza de la biología","127 Formación docente para la enseñanza de asignaturas específicas",62),
            new CamposProgramas("• Enseñanza de la literatura","127 Formación docente para la enseñanza de asignaturas específicas",63),
            new CamposProgramas("• Enseñanza del español","127 Formación docente para la enseñanza de asignaturas específicas",64),
            new CamposProgramas("128 Formación docente para otros servicios educativos",65),
            new CamposProgramas("12801 Formación docente para educación inicial",66),
            new CamposProgramas("• Educación infantil","128 Formación docente para otros servicios educativos",67),
            new CamposProgramas("• Puericultura","128 Formación docente para otros servicios educativos",68),
            new CamposProgramas("12802 Formación docente para educación especial",69),
            new CamposProgramas("• Desarrollo de la motricidad","128 Formación docente para otros servicios educativos",70),
            new CamposProgramas("• Educación en problemas de aprendizaje","128 Formación docente para otros servicios educativos",71),
            new CamposProgramas("• Educación especial en área visual, motriz","128 Formación docente para otros servicios educativos",72),
            new CamposProgramas("12803 Formación docente en educación para adultos",73),
            new CamposProgramas("• Docencia en educación para adultos","128 Formación docente para otros servicios educativos",74),
            new CamposProgramas("120 Formación docente, programas multidisciplinarios o generales",75),
            new CamposProgramas("• Docencia","120 Formación docente, programas multidisciplinarios o generales",76),
            new CamposProgramas("• Enseñanza","120 Formación docente, programas multidisciplinarios o generales",77),
            new CamposProgramas("21 Artes",78),
            new CamposProgramas("211 Bellas artes",79),
            new CamposProgramas("• Apreciación de las artes y estética","211 Bellas artes",80),
            new CamposProgramas("• Arte moderno y contemporáneo","211 Bellas artes",81),
            new CamposProgramas("• Artes plásticas","211 Bellas artes",82),
            new CamposProgramas("• Conservación y restauración de bienes muebles","211 Bellas artes",83),
            new CamposProgramas("212 Música y artes escénicas",84),
            new CamposProgramas("• Arte dramático","212 Música y artes escénicas",85),
            new CamposProgramas("• Artes escénicas y teatrales","212 Música y artes escénicas",86),
            new CamposProgramas("• Coreografía","212 Música y artes escénicas",87),
            new CamposProgramas("• Danza","212 Música y artes escénicas",88),
            new CamposProgramas("• Dirección artística, musical y de actuación","212 Música y artes escénicas",89),
            new CamposProgramas("• Historia de la música","212 Música y artes escénicas",90),
            new CamposProgramas("• Historia del cine y el teatro","212 Música y artes escénicas",91),
            new CamposProgramas("• Música (composición, instrumentista, concertista)","212 Música y artes escénicas",92),
            new CamposProgramas("213 Técnicas audiovisuales y producción de medios",93),
            new CamposProgramas("• Artes visuales y gráficas","213 Técnicas audiovisuales y producción de medios",94),
            new CamposProgramas("• Cinematografía","213 Técnicas audiovisuales y producción de medios",95),
            new CamposProgramas("• Diseño editorial","213 Técnicas audiovisuales y producción de medios",96),
            new CamposProgramas("• Diseño gráfico, multimedia e interactivo","213 Técnicas audiovisuales y producción de medios",97),
            new CamposProgramas("• Diseño y producción publicitario","213 Técnicas audiovisuales y producción de medios",98),
            new CamposProgramas("• Fotografía","213 Técnicas audiovisuales y producción de medios",99),
            new CamposProgramas("• Ilustración y caricatura","213 Técnicas audiovisuales y producción de medios",100),
            new CamposProgramas("• Sistemas de impresión y offset","213 Técnicas audiovisuales y producción de medios",101),
            new CamposProgramas("• Técnica de sonido","213 Técnicas audiovisuales y producción de medios",102),
            new CamposProgramas("• Técnicas audiovisuales","213 Técnicas audiovisuales y producción de medios",103),
            new CamposProgramas("214 Diseño",104),
            new CamposProgramas("• Arquitectura de interiores","214 Diseño",105),
            new CamposProgramas("• Corte y confección como diseño","214 Diseño",106),
            new CamposProgramas("• Diseño de artefactos-objetos (productos industriales)","214 Diseño",107),
            new CamposProgramas("• Diseño de indumentaria","214 Diseño",108),
            new CamposProgramas("• Diseño de interiores","214 Diseño",109),
            new CamposProgramas("• Diseño de modas","214 Diseño",110),
            new CamposProgramas("• Diseño textil o de calzado","214 Diseño",111),
            new CamposProgramas("• Sastrería","214 Diseño",112),
            new CamposProgramas("215 Técnicas y habilidades artesanales",113),
            new CamposProgramas("• Artes en vidrio","215 Técnicas y habilidades artesanales",114),
            new CamposProgramas("• Artes populares","215 Técnicas y habilidades artesanales",115),
            new CamposProgramas("• Cerámica y esmaltes","215 Técnicas y habilidades artesanales",116),
            new CamposProgramas("• Ebanistería","215 Técnicas y habilidades artesanales",117),
            new CamposProgramas("• Elaboración de instrumentos musicales","215 Técnicas y habilidades artesanales",118),
            new CamposProgramas("• Floristería","215 Técnicas y habilidades artesanales",119),
            new CamposProgramas("• Laudería","215 Técnicas y habilidades artesanales",120),
            new CamposProgramas("• Objetos metálicos decorativos","215 Técnicas y habilidades artesanales",121),
            new CamposProgramas("• Orfebrería","215 Técnicas y habilidades artesanales",122),
            new CamposProgramas("• Tallado de piedra","215 Técnicas y habilidades artesanales",123),
            new CamposProgramas("• Textiles artesanales","215 Técnicas y habilidades artesanales",124),
            new CamposProgramas("210 Artes, programas multidisciplinarios o generales",125),
            new CamposProgramas("• Apreciación de las artes","210 Artes, programas multidisciplinarios o generales",126),
            new CamposProgramas("• Artes","210 Artes, programas multidisciplinarios o generales",127),
            new CamposProgramas("• Patrimonio cultural","210 Artes, programas multidisciplinarios o generales",128),
            new CamposProgramas("22 Humanidades",129),
            new CamposProgramas("221 Teología",130),
            new CamposProgramas("• Ciencias religiosas","221 Teología",131),
            new CamposProgramas("• Filosofía de las religiones","221 Teología",132),
            new CamposProgramas("• Historia de las religiones","221 Teología",133),
            new CamposProgramas("222 Lenguas extranjeras",134),
            new CamposProgramas("• Interpretación","222 Lenguas extranjeras",135),
            new CamposProgramas("• Lenguas extranjeras","222 Lenguas extranjeras",136),
            new CamposProgramas("• Lenguas modernas","222 Lenguas extranjeras",137),
            new CamposProgramas("• Lenguas muertas","222 Lenguas extranjeras",138),
            new CamposProgramas("• Traducción","222 Lenguas extranjeras",139),
            new CamposProgramas("223 Literatura",140),
            new CamposProgramas("• Lengua materna (español)","223 Literatura",141),
            new CamposProgramas("• Lengua y literatura","223 Literatura",142),
            new CamposProgramas("• Lenguas indígenas","223 Literatura",143),
            new CamposProgramas("• Letras","223 Literatura",144),
            new CamposProgramas("• Lingüística","223 Literatura",145),
            new CamposProgramas("224 Historia y arqueología",146),
            new CamposProgramas("• Arqueología","224 Historia y arqueología",147),
            new CamposProgramas("• Estudios internacionales","224 Historia y arqueología",148),
            new CamposProgramas("• Estudios latinoamericanos","224 Historia y arqueología",149),
            new CamposProgramas("• Estudios regionales o de países","224 Historia y arqueología",150),
            new CamposProgramas("• Historia (de México, regional, universal)","224 Historia y arqueología",151),
            new CamposProgramas("• Historiografía","224 Historia y arqueología",152),
            new CamposProgramas("225 Filosofía y ética",153),
            new CamposProgramas("• Bioética","225 Filosofía y ética",154),
            new CamposProgramas("• Epistemología","225 Filosofía y ética",155),
            new CamposProgramas("• Lógica formal","225 Filosofía y ética",156),
            new CamposProgramas("• Metafísica","225 Filosofía y ética",157),
            new CamposProgramas("• Moral y valores","225 Filosofía y ética",158),
            new CamposProgramas("• Razonamiento lógico","225 Filosofía y ética",159),
            new CamposProgramas("220 Humanidades, programas multidisciplinarios o generales",160),
            new CamposProgramas("• Ciencias del hombre","220 Humanidades, programas multidisciplinarios o generales",161),
            new CamposProgramas("• Humanidades y artes","220 Humanidades, programas multidisciplinarios o generales",162),
            new CamposProgramas("• Teoría crítica","220 Humanidades, programas multidisciplinarios o generales",163),
            new CamposProgramas("31 Ciencias sociales y estudios del comportamiento",164),
            new CamposProgramas("311 Psicología",165),
            new CamposProgramas("• Parapsicología","311 Psicología",166),
            new CamposProgramas("• Psicoanálisis","311 Psicología",167),
            new CamposProgramas("• Psicobiología","311 Psicología",168),
            new CamposProgramas("• Psicolingüística","311 Psicología",169),
            new CamposProgramas("• Psicología clínica","311 Psicología",170),
            new CamposProgramas("• Psicología criminal","311 Psicología",171),
            new CamposProgramas("• Psicología cultural","311 Psicología",172),
            new CamposProgramas("• Psicología industrial y laboral","311 Psicología",173),
            new CamposProgramas("• Psicología social","311 Psicología",174),
            new CamposProgramas("• Psicoterapia familiar","311 Psicología",175),
            new CamposProgramas("• Psicoterapia","311 Psicología",176),
            new CamposProgramas("312 Sociología y antropología",177),
            new CamposProgramas("• Antropología estructural","312 Sociología y antropología",178),
            new CamposProgramas("• Antropología física","312 Sociología y antropología",179),
            new CamposProgramas("• Antropología social","312 Sociología y antropología",180),
            new CamposProgramas("• Demografía y estudios de población","312 Sociología y antropología",181),
            new CamposProgramas("• Desarrollo humano y ciencias sociales","312 Sociología y antropología",182),
            new CamposProgramas("• Desarrollo social, rural, regional, comunitario","312 Sociología y antropología",183),
            new CamposProgramas("• Etnología","312 Sociología y antropología",184),
            new CamposProgramas("• Evaluación de organizaciones y políticas públicas","312 Sociología y antropología",185),
            new CamposProgramas("• Geografía humana (social y cultural)","312 Sociología y antropología",186),
            new CamposProgramas("• Lingüística antropológica","312 Sociología y antropología",187),
            new CamposProgramas("• Metodología de investigación social (cuantitativa y cualitativa)","312 Sociología y antropología",188),
            new CamposProgramas("• Sociología de la cultura","312 Sociología y antropología",189),
            new CamposProgramas("• Sociología del trabajo","312 Sociología y antropología",190),
            new CamposProgramas("• Sociología industrial","312 Sociología y antropología",191),
            new CamposProgramas("• Sociología política","312 Sociología y antropología",192),
            new CamposProgramas("313 Ciencias políticas",193),
            new CamposProgramas("• Ciencias sociales y política","313 Ciencias políticas",194),
            new CamposProgramas("• Derechos humanos","313 Ciencias políticas",195),
            new CamposProgramas("• Economía y política","313 Ciencias políticas",196),
            new CamposProgramas("• Estudios electorales","313 Ciencias políticas",197),
            new CamposProgramas("• Estudios políticos","313 Ciencias políticas",198),
            new CamposProgramas("• Estudios sobre la paz y conflictos","313 Ciencias políticas",199),
            new CamposProgramas("• Filosofía política","313 Ciencias políticas",200),
            new CamposProgramas("• Historia política","313 Ciencias políticas",201),
            new CamposProgramas("• Relaciones internacionales","313 Ciencias políticas",202),
            new CamposProgramas("314 Economía",203),
            new CamposProgramas("• Desarrollo económico","314 Economía",204),
            new CamposProgramas("• Economía agrícola","314 Economía",205),
            new CamposProgramas("• Economía cuantitativa","314 Economía",206),
            new CamposProgramas("• Economía de la educación","314 Economía",207),
            new CamposProgramas("• Economía del sector público","314 Economía",208),
            new CamposProgramas("• Economía del trabajo","314 Economía",209),
            new CamposProgramas("• Economía industrial","314 Economía",210),
            new CamposProgramas("• Economía internacional","314 Economía",211),
            new CamposProgramas("• Economía política","314 Economía",212),
            new CamposProgramas("• Economía y administración","314 Economía",213),
            new CamposProgramas("• Economía y finanzas","314 Economía",214),
            new CamposProgramas("• Planeación económica y rural","314 Economía",215),
            new CamposProgramas("• Política económica","314 Economía",216),
            new CamposProgramas("• Teoría económica","314 Economía",217),
            new CamposProgramas("315 Trabajo y atención social",218),
            new CamposProgramas("• Atención a la violencia familiar","315 Trabajo y atención social",219),
            new CamposProgramas("• Ciencias de la familia","315 Trabajo y atención social",220),
            new CamposProgramas("• Consultoría familiar","315 Trabajo y atención social",221),
            new CamposProgramas("• Orientación familiar y matrimonial","315 Trabajo y atención social",222),
            new CamposProgramas("• Prevención en el consumo de drogas y alcohol","315 Trabajo y atención social",223),
            new CamposProgramas("310 Ciencias sociales y estudios del comportamiento, programas multidisciplinarios o generales",224),
            new CamposProgramas("• Ciencias sociales","310 Ciencias sociales y estudios del comportamiento, programas multidisciplinarios o generales",225),
            new CamposProgramas("• Estudios sociales y humanos","310 Ciencias sociales y estudios del comportamiento, programas multidisciplinarios o generales",226),
            new CamposProgramas("32 Ciencias de la información",227),
            new CamposProgramas("321 Comunicación y periodismo",228),
            new CamposProgramas("• Ciencias de la comunicación","321 Comunicación y periodismo",229),
            new CamposProgramas("• Comunicación organizacional","321 Comunicación y periodismo",230),
            new CamposProgramas("• Comunicación política","321 Comunicación y periodismo",231),
            new CamposProgramas("• Crítica periodística","321 Comunicación y periodismo",232),
            new CamposProgramas("• Fotoperiodismo","321 Comunicación y periodismo",233),
            new CamposProgramas("• Medios masivos de comunicación","321 Comunicación y periodismo",234),
            new CamposProgramas("• Periodismo","321 Comunicación y periodismo",235),
            new CamposProgramas("322 Biblioteconomía",236),
            new CamposProgramas("• Archivonomía","322 Biblioteconomía",237),
            new CamposProgramas("• Bibliotecnología","322 Biblioteconomía",238),
            new CamposProgramas("• Ciencias de información documental","322 Biblioteconomía",239),
            new CamposProgramas("• Sistemas y servicios bibliotecarios","322 Biblioteconomía",240),
            new CamposProgramas("33 Negocios y administración",241),
            new CamposProgramas("331 Negocios y comercio",242),
            new CamposProgramas("• Aduanas","331 Negocios y comercio",243),
            new CamposProgramas("• Agronegocios","331 Negocios y comercio",244),
            new CamposProgramas("• Comercio electrónico","331 Negocios y comercio",245),
            new CamposProgramas("• Comercio exterior","331 Negocios y comercio",246),
            new CamposProgramas("• Comercio global","331 Negocios y comercio",247),
            new CamposProgramas("• Comercio internacional","331 Negocios y comercio",248),
            new CamposProgramas("• Consultoría de negocios","331 Negocios y comercio",249),
            new CamposProgramas("• Desarrollo de negocios","331 Negocios y comercio",250),
            new CamposProgramas("• Negociación","331 Negocios y comercio",251),
            new CamposProgramas("• Negocios electrónicos","331 Negocios y comercio",252),
            new CamposProgramas("• Negocios internacionales","331 Negocios y comercio",253),
            new CamposProgramas("• Valuación","331 Negocios y comercio",254),
            new CamposProgramas("332 Mercadotecnia y publicidad",255),
            new CamposProgramas("• Marketing","332 Mercadotecnia y publicidad",256),
            new CamposProgramas("• Mercadotecnia y comercio","332 Mercadotecnia y publicidad",257),
            new CamposProgramas("• Mercadotecnia y ventas","332 Mercadotecnia y publicidad",258),
            new CamposProgramas("• Publicidad estratégica","332 Mercadotecnia y publicidad",259),
            new CamposProgramas("• Publicidad y medios","332 Mercadotecnia y publicidad",260),
            new CamposProgramas("• Relaciones públicas","332 Mercadotecnia y publicidad",261),
            new CamposProgramas("• Sistemas comerciales","332 Mercadotecnia y publicidad",262),
            new CamposProgramas("• Ventas","332 Mercadotecnia y publicidad",263),
            new CamposProgramas("333 Finanzas, banca y seguros",264),
            new CamposProgramas("• Banca y mercados","333 Finanzas, banca y seguros",265),
            new CamposProgramas("• Finanzas corporativas","333 Finanzas, banca y seguros",266),
            new CamposProgramas("• Finanzas empresariales","333 Finanzas, banca y seguros",267),
            new CamposProgramas("• Finanzas y negocios","333 Finanzas, banca y seguros",268),
            new CamposProgramas("• Mercados financieros","333 Finanzas, banca y seguros",269),
            new CamposProgramas("• Proyectos de inversión","333 Finanzas, banca y seguros",270),
            new CamposProgramas("• Seguros, daños y ajustes","333 Finanzas, banca y seguros",271),
            new CamposProgramas("334 Contabilidad y fiscalización",272),
            new CamposProgramas("• Análisis tributario","334 Contabilidad y fiscalización",273),
            new CamposProgramas("• Auditoría","334 Contabilidad y fiscalización",274),
            new CamposProgramas("• Contabilidad administrativa","334 Contabilidad y fiscalización",275),
            new CamposProgramas("• Contabilidad financiera","334 Contabilidad y fiscalización",276),
            new CamposProgramas("• Contabilidad fiscal","334 Contabilidad y fiscalización",277),
            new CamposProgramas("• Contador privado","334 Contabilidad y fiscalización",278),
            new CamposProgramas("• Contaduría pública","334 Contabilidad y fiscalización",279),
            new CamposProgramas("• Contribuciones","334 Contabilidad y fiscalización",280),
            new CamposProgramas("• Hacienda pública","334 Contabilidad y fiscalización",281),
            new CamposProgramas("335 Administración y gestión de empresas",282),
            new CamposProgramas("33501 Administración de sistemas educativos",283),
            new CamposProgramas("• Administración de instituciones escolares","335 Administración y gestión de empresas",284),
            new CamposProgramas("• Administración de la educación","335 Administración y gestión de empresas",285),
            new CamposProgramas("• Dirección de centros educativos","335 Administración y gestión de empresas",286),
            new CamposProgramas("• Gestión o supervisión de instituciones educativas","335 Administración y gestión de empresas",287),
            new CamposProgramas("33502 Administración de empresas",288),
            new CamposProgramas("• Administración de empresas","335 Administración y gestión de empresas",289),
            new CamposProgramas("• Administración de organizaciones","335 Administración y gestión de empresas",290),
            new CamposProgramas("• Administración de recursos humanos","335 Administración y gestión de empresas",291),
            new CamposProgramas("• Gestión de empresas e instituciones","335 Administración y gestión de empresas",292),
            new CamposProgramas("33503 Administración pública",293),
            new CamposProgramas("• Administración pública municipal","335 Administración y gestión de empresas",294),
            new CamposProgramas("• Administración y políticas públicas","335 Administración y gestión de empresas",295),
            new CamposProgramas("• Gerencia pública","335 Administración y gestión de empresas",296),
            new CamposProgramas("• Gobierno y administración pública","335 Administración y gestión de empresas",297),
            new CamposProgramas("33504 Administración en el campo de la ingeniería y la construcción",298),
            new CamposProgramas("• Administración de la construcción","335 Administración y gestión de empresas",299),
            new CamposProgramas("• Administración de la obra","335 Administración y gestión de empresas",300),
            new CamposProgramas("• Administración industrial","335 Administración y gestión de empresas",301),
            new CamposProgramas("• Ingeniería industrial en administración","335 Administración y gestión de empresas",302),
            new CamposProgramas("33505 Administración en el campo de la agronomía",303),
            new CamposProgramas("• Administración de empresas agropecuarias","335 Administración y gestión de empresas",304),
            new CamposProgramas("• Administración de empresas marinas","335 Administración y gestión de empresas",305),
            new CamposProgramas("• Administración de organizaciones marinas","335 Administración y gestión de empresas",306),
            new CamposProgramas("33506 Administración en el campo de la salud",307),
            new CamposProgramas("• Administración de hospitales","335 Administración y gestión de empresas",308),
            new CamposProgramas("• Administración de recursos para la salud","335 Administración y gestión de empresas",309),
            new CamposProgramas("• Gestión de organizaciones de atención de la salud","335 Administración y gestión de empresas",310),
            new CamposProgramas("• Gestión hospitalaria","335 Administración y gestión de empresas",311),
            new CamposProgramas("33507 Administración turística",312),
            new CamposProgramas("• Administración de la hospitalidad","335 Administración y gestión de empresas",313),
            new CamposProgramas("• Administración del tiempo libre","335 Administración y gestión de empresas",314),
            new CamposProgramas("• Administración turística","335 Administración y gestión de empresas",315),
            new CamposProgramas("• Agencia de viajes","335 Administración y gestión de empresas",316),
            new CamposProgramas("• Hotelería","335 Administración y gestión de empresas",317),
            new CamposProgramas("• Recreación","335 Administración y gestión de empresas",318),
            new CamposProgramas("• Servicios de hospitalidad","335 Administración y gestión de empresas",319),
            new CamposProgramas("• Turismo y servicios turísticos","335 Administración y gestión de empresas",320),
            new CamposProgramas("33508 Administración de restaurantes y gastronomía",321),
            new CamposProgramas("• Artes culinarias","335 Administración y gestión de empresas",322),
            new CamposProgramas("• Empresas gastronómicas","335 Administración y gestión de empresas",323),
            new CamposProgramas("• Gastronomía","335 Administración y gestión de empresas",324),
            new CamposProgramas("• Gestión de restaurantes","335 Administración y gestión de empresas",325),
            new CamposProgramas("• Servicio de alimentos y bebidas","335 Administración y gestión de empresas",326),
            new CamposProgramas("• Servicios de restaurantes","335 Administración y gestión de empresas",327),
            new CamposProgramas("33509 Administración en el campo de artes y humanidades",328),
            new CamposProgramas("• Administración de galerías de arte","335 Administración y gestión de empresas",329),
            new CamposProgramas("• Administración de museos","335 Administración y gestión de empresas",330),
            new CamposProgramas("33510 Administración en el campo del deporte",331),
            new CamposProgramas("• Administración de asociaciones deportivas","335 Administración y gestión de empresas",332),
            new CamposProgramas("• Administración de clubes deportivos","335 Administración y gestión de empresas",333),
            new CamposProgramas("330 Negocios y administración, programas multidisciplinarios o generales",334),
            new CamposProgramas("• Administración","330 Negocios y administración, programas multidisciplinarios o generales",335),
            new CamposProgramas("• Administración de la filantropía","330 Negocios y administración, programas multidisciplinarios o generales",336),
            new CamposProgramas("• Dirección global","330 Negocios y administración, programas multidisciplinarios o generales",337),
            new CamposProgramas("• Liderazgo","330 Negocios y administración, programas multidisciplinarios o generales",338),
            new CamposProgramas("• Responsabilidad social","330 Negocios y administración, programas multidisciplinarios o generales",339),
            new CamposProgramas("34 Derecho",340),
            new CamposProgramas("341 Derecho",341),
            new CamposProgramas("• Abogacía","341 Derecho",342),
            new CamposProgramas("• Administración y procuración de justicia","341 Derecho",343),
            new CamposProgramas("• Ciencias penales","341 Derecho",344),
            new CamposProgramas("• Defensa fiscal","341 Derecho",345),
            new CamposProgramas("• Derecho administrativo","341 Derecho",346),
            new CamposProgramas("• Derecho agrario y minero","341 Derecho",347),
            new CamposProgramas("• Derecho civil","341 Derecho",348),
            new CamposProgramas("• Derecho financiero","341 Derecho",349),
            new CamposProgramas("•  Derecho internacional","341 Derecho",350),
            new CamposProgramas("•  Derecho laboral","341 Derecho",351),
            new CamposProgramas("•  Derecho mercantil","341 Derecho",352),
            new CamposProgramas("•  Derecho migratorio","341 Derecho",353),
            new CamposProgramas("•  Derecho procesal","341 Derecho",354),
            new CamposProgramas("• Derecho social","341 Derecho",355),
            new CamposProgramas("•  Derecho tributario","341 Derecho",356),
            new CamposProgramas("•  Jurisprudencia","341 Derecho",357),
            new CamposProgramas("• Procuración de justicia","341 Derecho",358),
            new CamposProgramas("342 Criminología",359),
            new CamposProgramas("•  Ciencias periciales","342 Criminología",360),
            new CamposProgramas("•  Criminalística","342 Criminología",361),
            new CamposProgramas("•  Crimino-victimología","342 Criminología",362),
            new CamposProgramas("•  Dactiloscopía","342 Criminología",363),
            new CamposProgramas("41 Ciencias naturales",364),
            new CamposProgramas("411 Biología y bioquímica",365),
            new CamposProgramas("• Anatomía","411 Biología y bioquímica",366),
            new CamposProgramas("• Biofísica","411 Biología y bioquímica",367),
            new CamposProgramas("• Biología marina","411 Biología y bioquímica",368),
            new CamposProgramas("• Botánica","411 Biología y bioquímica",369),
            new CamposProgramas("• Ciencias biomédicas","411 Biología y bioquímica",370),
            new CamposProgramas("• Ciencias genómicas","411 Biología y bioquímica",371),
            new CamposProgramas("• Citología","411 Biología y bioquímica",372),
            new CamposProgramas("• Embriología","411 Biología y bioquímica",373),
            new CamposProgramas("• Farmacología","411 Biología y bioquímica",374),
            new CamposProgramas("• Fisiología","411 Biología y bioquímica",375),
            new CamposProgramas("• Genética","411 Biología y bioquímica",376),
            new CamposProgramas("• Genómica","411 Biología y bioquímica",377),
            new CamposProgramas("• Hidrobiología","411 Biología y bioquímica",378),
            new CamposProgramas("• Histología","411 Biología y bioquímica",379),
            new CamposProgramas("• Inmunología","411 Biología y bioquímica",380),
            new CamposProgramas("• Microbiología","411 Biología y bioquímica",381),
            new CamposProgramas("• Parasitología","411 Biología y bioquímica",382),
            new CamposProgramas("• Radiobiología","411 Biología y bioquímica",383),
            new CamposProgramas("• Toxicología","411 Biología y bioquímica",384),
            new CamposProgramas("• Zoología","411 Biología y bioquímica",385),
            new CamposProgramas("412 Ciencias ambientales",386),
            new CamposProgramas("• Ecología","412 Ciencias ambientales",387),
            new CamposProgramas("• Ecología marina","412 Ciencias ambientales",388),
            new CamposProgramas("• Ecología tropical","412 Ciencias ambientales",389),
            new CamposProgramas("• Gestión ambiental","412 Ciencias ambientales",390),
            new CamposProgramas("• Limnología","412 Ciencias ambientales",391),
            new CamposProgramas("• Manejo ambiental y de la fauna","412 Ciencias ambientales",392),
            new CamposProgramas("• Recursos naturales y medio ambiente","412 Ciencias ambientales",393),
            new CamposProgramas("42 Ciencias físicas, químicas y de la tierra",394),
            new CamposProgramas("421 Física",395),
            new CamposProgramas("• Astronomía","421 Física",396),
            new CamposProgramas("• Ciencias del espacio","421 Física",397),
            new CamposProgramas("• Física aplicada","421 Física",398),
            new CamposProgramas("• Física atómica y molecular","421 Física",399),
            new CamposProgramas("• Física de materiales","421 Física",400),
            new CamposProgramas("• Física matemática","421 Física",401),
            new CamposProgramas("• Física médica","421 Física",402),
            new CamposProgramas("• Física nuclear","421 Física",403),
            new CamposProgramas("• Física teórica","421 Física",404),
            new CamposProgramas("• Mecánica clásica y cuántica","421 Física",405),
            new CamposProgramas("• Mecánica estadística","421 Física",406),
            new CamposProgramas("• Óptica","421 Física",407),
            new CamposProgramas("• Plasmas","421 Física",408),
            new CamposProgramas("• Termofísica","421 Física",409),
            new CamposProgramas("422 Química",410),
            new CamposProgramas("• Ciencias de materiales","422 Química",411),
            new CamposProgramas("• Materiales avanzados","422 Química",412),
            new CamposProgramas("• Nanotecnología","422 Química",413),
            new CamposProgramas("• Química analítica","422 Química",414),
            new CamposProgramas("• Química nuclear","422 Química",415),
            new CamposProgramas("• Química orgánica e inorgánica","422 Química",416),
            new CamposProgramas("423 Ciencias de la tierra y de la atmósfera",417),
            new CamposProgramas("• Ciencias atmosféricas","423 Ciencias de la tierra y de la atmósfera",418),
            new CamposProgramas("• Geofísica","423 Ciencias de la tierra y de la atmósfera",419),
            new CamposProgramas("• Geología","423 Ciencias de la tierra y de la atmósfera",420),
            new CamposProgramas("• Geomagnetismo","423 Ciencias de la tierra y de la atmósfera",421),
            new CamposProgramas("• Geomática","423 Ciencias de la tierra y de la atmósfera",422),
            new CamposProgramas("• Geotecnia","423 Ciencias de la tierra y de la atmósfera",423),
            new CamposProgramas("• Hidrología","423 Ciencias de la tierra y de la atmósfera",424),
            new CamposProgramas("• Meteorología","423 Ciencias de la tierra y de la atmósfera",425),
            new CamposProgramas("• Oceanografía","423 Ciencias de la tierra y de la atmósfera",426),
            new CamposProgramas("• Sismología","423 Ciencias de la tierra y de la atmósfera",427),
            new CamposProgramas("43 Matemáticas y estadística",428),
            new CamposProgramas("431 Matemáticas",429),
            new CamposProgramas("• Álgebra","431 Matemáticas",430),
            new CamposProgramas("• Análisis numérico y funcional","431 Matemáticas",431),
            new CamposProgramas("• Geometría","431 Matemáticas",432),
            new CamposProgramas("• Matemáticas aplicadas","431 Matemáticas",433),
            new CamposProgramas("• Matemáticas y economía","431 Matemáticas",434),
            new CamposProgramas("• Sistemas complejos","431 Matemáticas",435),
            new CamposProgramas("• Topología","431 Matemáticas",436),
            new CamposProgramas("432 Estadística",437),
            new CamposProgramas("• Actuaría","432 Estadística",438),
            new CamposProgramas("• Análisis estadístico","432 Estadística",439),
            new CamposProgramas("• Diseño muestral","432 Estadística",440),
            new CamposProgramas("• Estadística aplicada","432 Estadística",441),
            new CamposProgramas("• Probabilidad","432 Estadística",442),
            new CamposProgramas("44 Ciencias de la computación",443),
            new CamposProgramas("441 Ciencias de la computación",444),
            new CamposProgramas("• Administración de computación","441 Ciencias de la computación",445),
            new CamposProgramas("• Administración de redes","441 Ciencias de la computación",446),
            new CamposProgramas("• Análisis de sistemas de cómputo","441 Ciencias de la computación",447),
            new CamposProgramas("• Arquitectura o desarrollo de software","441 Ciencias de la computación",448),
            new CamposProgramas("• Computación","441 Ciencias de la computación",449),
            new CamposProgramas("• Diseño de sistemas de cómputo","441 Ciencias de la computación",450),
            new CamposProgramas("• Informática","441 Ciencias de la computación",451),
            new CamposProgramas("• Lenguajes de programación","441 Ciencias de la computación",452),
            new CamposProgramas("• Ofimática","441 Ciencias de la computación",453),
            new CamposProgramas("• Programación de cómputo","441 Ciencias de la computación",454),
            new CamposProgramas("• Sistemas operativos","441 Ciencias de la computación",455),
            new CamposProgramas("51 Ingeniería industrial, mecánica, electrónica y tecnología",456),
            new CamposProgramas("511 Ingeniería mecánica y metalurgia",457),
            new CamposProgramas("• Control de procesos de producción","511 Ingeniería mecánica y metalurgia",458),
            new CamposProgramas("• Control de sistemas y dispositivos industriales","511 Ingeniería mecánica y metalurgia",459),
            new CamposProgramas("• Dibujo mecánico industrial","511 Ingeniería mecánica y metalurgia",460),
            new CamposProgramas("• Diseño industrial de productos metálicos (armamento, herramientas, entre otros)","511 Ingeniería mecánica y metalurgia",461),
            new CamposProgramas("• Física industrial","511 Ingeniería mecánica y metalurgia",462),
            new CamposProgramas("• Fundición de metales y patrones","511 Ingeniería mecánica y metalurgia",463),
            new CamposProgramas("• Herramientas y matrices","511 Ingeniería mecánica y metalurgia",464),
            new CamposProgramas("• Ingeniería hidráulica y agrohidráulica","511 Ingeniería mecánica y metalurgia",465),
            new CamposProgramas("• Ingeniería industrial de mantenimiento","511 Ingeniería mecánica y metalurgia",466),
            new CamposProgramas("• Ingeniería industrial en mecánica","511 Ingeniería mecánica y metalurgia",467),
            new CamposProgramas("• Ingeniería mecánica eléctrica","511 Ingeniería mecánica y metalurgia",468),
            new CamposProgramas("• Ingeniería metalúrgica","511 Ingeniería mecánica y metalurgia",469),
            new CamposProgramas("• Mecánica de precisión","511 Ingeniería mecánica y metalurgia",470),
            new CamposProgramas("• Mecatrónica","511 Ingeniería mecánica y metalurgia",471),
            new CamposProgramas("• Montaje, mecanizado y torneado de metales","511 Ingeniería mecánica y metalurgia",472),
            new CamposProgramas("• Sistemas de calidad mecánica y metalúrgica","511 Ingeniería mecánica y metalurgia",473),
            new CamposProgramas("• Soldadura industrial","511 Ingeniería mecánica y metalurgia",474),
            new CamposProgramas("• Tecnología de los materiales","511 Ingeniería mecánica y metalurgia",475),
            new CamposProgramas("512 Electricidad y generación de energía",476),
            new CamposProgramas("• Aire acondicionado y refrigeración","512 Electricidad y generación de energía",477),
            new CamposProgramas("• Automatización y control de energía eléctrica","512 Electricidad y generación de energía",478),
            new CamposProgramas("• Electromecánica","512 Electricidad y generación de energía",479),
            new CamposProgramas("• Energía eólica y solar","512 Electricidad y generación de energía",480),
            new CamposProgramas("• Energía nuclear","512 Electricidad y generación de energía",481),
            new CamposProgramas("• Energía renovable","512 Electricidad y generación de energía",482),
            new CamposProgramas("• Energía térmica","512 Electricidad y generación de energía",483),
            new CamposProgramas("• Ingeniería eléctrica","512 Electricidad y generación de energía",484),
            new CamposProgramas("• Ingeniería energética","512 Electricidad y generación de energía",485),
            new CamposProgramas("• Instalación eléctrica e iluminación","512 Electricidad y generación de energía",486),
            new CamposProgramas("• Instalación y mantenimiento de la red eléctrica","512 Electricidad y generación de energía",487),
            new CamposProgramas("• Mantenimiento eléctrico","512 Electricidad y generación de energía",488),
            new CamposProgramas("• Producción de energía","512 Electricidad y generación de energía",489),
            new CamposProgramas("• Programas comerciales de electricidad","512 Electricidad y generación de energía",490),
            new CamposProgramas("513 Electrónica y automatización",491),
            new CamposProgramas("• Automatización","513 Electrónica y automatización",492),
            new CamposProgramas("• Electrónica médica (electromédica)","513 Electrónica y automatización",493),
            new CamposProgramas("• Ingeniería de control","513 Electrónica y automatización",494),
            new CamposProgramas("• Ingeniería industrial en electrónica","513 Electrónica y automatización",495),
            new CamposProgramas("• Ingeniería robótica","513 Electrónica y automatización",496),
            new CamposProgramas("• Inteligencia artificial","513 Electrónica y automatización",497),
            new CamposProgramas("• Microelectrónica","513 Electrónica y automatización",498),
            new CamposProgramas("514 Ingeniería química",499),
            new CamposProgramas("• Biotecnología","514 Ingeniería química",500),
            new CamposProgramas("• Ingeniería industrial química","514 Ingeniería química",501),
            new CamposProgramas("• Ingeniería petroquímica","514 Ingeniería química",502),
            new CamposProgramas("• Ingeniería química (industrial, petrolera)","514 Ingeniería química",503),
            new CamposProgramas("• Operación de plantas y maquinaria (transformación)","514 Ingeniería química",504),
            new CamposProgramas("• Tecnología de laboratorios químicos","514 Ingeniería química",505),
            new CamposProgramas("• Tecnología de procesos petroquímicos","514 Ingeniería química",506),
            new CamposProgramas("• Tecnologías bioquímicas","514 Ingeniería química",507),
            new CamposProgramas("515 Ingeniería de vehículos de motor, barcos y aeronaves",508),
            new CamposProgramas("• Construcción de vehículos de motor","515 Ingeniería de vehículos de motor, barcos y aeronaves",509),
            new CamposProgramas("• Diseño de automóviles, barcos y aeronaves","515 Ingeniería de vehículos de motor, barcos y aeronaves",510),
            new CamposProgramas("• Electricidad automotriz","515 Ingeniería de vehículos de motor, barcos y aeronaves",511),
            new CamposProgramas("• Electrónica automotriz","515 Ingeniería de vehículos de motor, barcos y aeronaves",512),
            new CamposProgramas("• Hojalatería y pintura automotriz","515 Ingeniería de vehículos de motor, barcos y aeronaves",513),
            new CamposProgramas("• Ingeniería aeronáutica y aeroespacial","515 Ingeniería de vehículos de motor, barcos y aeronaves",514),
            new CamposProgramas("• Ingeniería automotriz","515 Ingeniería de vehículos de motor, barcos y aeronaves",515),
            new CamposProgramas("• Ingeniería naval","515 Ingeniería de vehículos de motor, barcos y aeronaves",516),
            new CamposProgramas("• Mantenimiento de aeronaves","515 Ingeniería de vehículos de motor, barcos y aeronaves",517),
            new CamposProgramas("• Maquinaria agrícola","515 Ingeniería de vehículos de motor, barcos y aeronaves",518),
            new CamposProgramas("• Mecánica agrícola","515 Ingeniería de vehículos de motor, barcos y aeronaves",519),
            new CamposProgramas("• Mecánica en equipo náutico","515 Ingeniería de vehículos de motor, barcos y aeronaves",520),
            new CamposProgramas("516 Tecnología y protección del medio ambiente",521),
            new CamposProgramas("• Diagnóstico ambiental","516 Tecnología y protección del medio ambiente",522),
            new CamposProgramas("• Ingeniería ambiental","516 Tecnología y protección del medio ambiente",523),
            new CamposProgramas("• Ingeniería ecológica","516 Tecnología y protección del medio ambiente",524),
            new CamposProgramas("• Procesos ambientales","516 Tecnología y protección del medio ambiente",525),
            new CamposProgramas("• Protección ambiental","516 Tecnología y protección del medio ambiente",526),
            new CamposProgramas("• Tecnología medioambiental","516 Tecnología y protección del medio ambiente",527),
            new CamposProgramas("517 Tecnologías de la información y la comunicación",528),
            new CamposProgramas("• Ingeniería de cómputo","517 Tecnologías de la información y la comunicación",529),
            new CamposProgramas("• Ingeniería de hardware","517 Tecnologías de la información y la comunicación",530),
            new CamposProgramas("• Instalación y mantenimiento a equipo de cómputo y telecomunicaciones","517 Tecnologías de la información y la comunicación",531),
            new CamposProgramas("• Radiodifusión electrónica","517 Tecnologías de la información y la comunicación",532),
            new CamposProgramas("• Tecnología de redes","517 Tecnologías de la información y la comunicación",533),
            new CamposProgramas("• Tecnologías web","517 Tecnologías de la información y la comunicación",534),
            new CamposProgramas("• Telefonía","517 Tecnologías de la información y la comunicación",535),
            new CamposProgramas("• Teleinformática","517 Tecnologías de la información y la comunicación",536),
            new CamposProgramas("• Telemática","517 Tecnologías de la información y la comunicación",537),
            new CamposProgramas("510 Ingeniería industrial, mecánica, electrónica y tecnología, programas multidisciplinarios o generales",538),
            new CamposProgramas("• Ciencia y tecnología","510 Ingeniería industrial, mecánica, electrónica y tecnología, programas multidisciplinarios o generales",539),
            new CamposProgramas("• Control de calidad","510 Ingeniería industrial, mecánica, electrónica y tecnología, programas multidisciplinarios o generales",540),
            new CamposProgramas("• Ingeniería industrial","510 Ingeniería industrial, mecánica, electrónica y tecnología, programas multidisciplinarios o generales",541),
            new CamposProgramas("• Tecnología avanzada","510 Ingeniería industrial, mecánica, electrónica y tecnología, programas multidisciplinarios o generales",542),
            new CamposProgramas("52 Manufacturas y procesos",543),
            new CamposProgramas("521 Industria de la alimentación",544),
            new CamposProgramas("• Ciencia y tecnología de los alimentos","521 Industria de la alimentación",545),
            new CamposProgramas("• Conservación y procesamiento de productos marinos","521 Industria de la alimentación",546),
            new CamposProgramas("• Ingeniería bioquímica de alimentos (fermentaciones)","521 Industria de la alimentación",547),
            new CamposProgramas("• Ingeniería fisicoquímica de los alimentos","521 Industria de la alimentación",548),
            new CamposProgramas("• Ingeniería industrial en alimentos","521 Industria de la alimentación",549),
            new CamposProgramas("• Ingeniería químico-biológicas de los alimentos","521 Industria de la alimentación",550),
            new CamposProgramas("• Preservación de alimentos","521 Industria de la alimentación",551),
            new CamposProgramas("• Procesamiento de alimentos y bebidas","521 Industria de la alimentación",552),
            new CamposProgramas("• Procesamiento de carne","521 Industria de la alimentación",553),
            new CamposProgramas("• Procesos agroindustriales","521 Industria de la alimentación",554),
            new CamposProgramas("• Química en alimentos","521 Industria de la alimentación",555),
            new CamposProgramas("• Química microbiológica de alimentos","521 Industria de la alimentación",556),
            new CamposProgramas("• Repostería/panificación industrial","521 Industria de la alimentación",557),
            new CamposProgramas("• Tecnología agroalimentaria","521 Industria de la alimentación",558),
            new CamposProgramas("• Tecnología de la leche y productos lácteos","521 Industria de la alimentación",559),
            new CamposProgramas("522 Industria textil, del calzado y piel",560),
            new CamposProgramas("• Ingeniería en industria del calzado","522 Industria textil, del calzado y piel",561),
            new CamposProgramas("• Ingeniería en industria del vestido","522 Industria textil, del calzado y piel",562),
            new CamposProgramas("• Ingeniería textil","522 Industria textil, del calzado y piel",563),
            new CamposProgramas("• Procesamiento de materia prima para tejidos y textiles","522 Industria textil, del calzado y piel",564),
            new CamposProgramas("• Tecnología para el grabado en cuero y piel","522 Industria textil, del calzado y piel",565),
            new CamposProgramas("• Tecnología para el tratamiento de cuero y piel","522 Industria textil, del calzado y piel",566),
            new CamposProgramas("• Tecnología para hilados, tejidos, bordados y tapicería","522 Industria textil, del calzado y piel",567),
            new CamposProgramas("523 Industrias de materiales diversos (madera, papel, plástico, vidrio)",568),
            new CamposProgramas("• Carpintería (no para edificaciones)","523 Industrias de materiales diversos (madera, papel, plástico, vidrio)",569),
            new CamposProgramas("• Manufacturas de caucho","523 Industrias de materiales diversos (madera, papel, plástico, vidrio)",570),
            new CamposProgramas("• Manufacturas de plástico","523 Industrias de materiales diversos (madera, papel, plástico, vidrio)",571),
            new CamposProgramas("• Procesamiento industrial con vidrio","523 Industrias de materiales diversos (madera, papel, plástico, vidrio)",572),
            new CamposProgramas("• Procesamiento y manufactura de papel","523 Industrias de materiales diversos (madera, papel, plástico, vidrio)",573),
            new CamposProgramas("• Producción de joyería en piedras finas","523 Industrias de materiales diversos (madera, papel, plástico, vidrio)",574),
            new CamposProgramas("• Tecnología de la cerámica (industrial)","523 Industrias de materiales diversos (madera, papel, plástico, vidrio)",575),
            new CamposProgramas("• Tecnología de polímeros","523 Industrias de materiales diversos (madera, papel, plástico, vidrio)",576),
            new CamposProgramas("• Tecnología y manufactura de la madera","523 Industrias de materiales diversos (madera, papel, plástico, vidrio)",577),
            new CamposProgramas("• Torneado y mecanizado de la madera","523 Industrias de materiales diversos (madera, papel, plástico, vidrio)",578),
            new CamposProgramas("524 Minería y extracción",579),
            new CamposProgramas("• Extracción de materias primas","524 Minería y extracción",580),
            new CamposProgramas("• Ingeniería de minas","524 Minería y extracción",581),
            new CamposProgramas("• Ingeniería geológica","524 Minería y extracción",582),
            new CamposProgramas("• Ingeniería petrolera y de gas","524 Minería y extracción",583),
            new CamposProgramas("• Tecnología de minerales","524 Minería y extracción",584),
            new CamposProgramas("520 Manufacturas y procesos, programas multidisciplinarios o generales",585),
            new CamposProgramas("• Ingeniería industrial en productividad","520 Manufacturas y procesos, programas multidisciplinarios o generales",586),
            new CamposProgramas("• Manufactura","520 Manufacturas y procesos, programas multidisciplinarios o generales",587),
            new CamposProgramas("• Sistemas de producción","520 Manufacturas y procesos, programas multidisciplinarios o generales",588),
            new CamposProgramas("53 Arquitectura y construcción",589),
            new CamposProgramas("531 Arquitectura y urbanismo",590),
            new CamposProgramas("• Arquitectura bioclimática","531 Arquitectura y urbanismo",591),
            new CamposProgramas("• Arquitectura del paisaje","531 Arquitectura y urbanismo",592),
            new CamposProgramas("• Arquitectura estructural","531 Arquitectura y urbanismo",593),
            new CamposProgramas("• Diseño arquitectónico","531 Arquitectura y urbanismo",594),
            new CamposProgramas("• Diseño de edificios","531 Arquitectura y urbanismo",595),
            new CamposProgramas("• Diseño urbano y del paisaje","531 Arquitectura y urbanismo",596),
            new CamposProgramas("• Expresión gráfica arquitectónica","531 Arquitectura y urbanismo",597),
            new CamposProgramas("• Ingeniería municipal","531 Arquitectura y urbanismo",598),
            new CamposProgramas("• Ordenamiento territorial","531 Arquitectura y urbanismo",599),
            new CamposProgramas("• Planeación urbana","531 Arquitectura y urbanismo",600),
            new CamposProgramas("• Planificación urbana y rural","531 Arquitectura y urbanismo",601),
            new CamposProgramas("• Rehabilitación y restauración arquitectónica","531 Arquitectura y urbanismo",602),
            new CamposProgramas("• Urbanismo ecológico","531 Arquitectura y urbanismo",603),
            new CamposProgramas("532 Construcción e ingeniería civil",604),
            new CamposProgramas("• Construcción de edificios","532 Construcción e ingeniería civil",605),
            new CamposProgramas("• Construcción de carreteras y puentes","532 Construcción e ingeniería civil",606),
            new CamposProgramas("• Construcción en metal","532 Construcción e ingeniería civil",607),
            new CamposProgramas("• Ingeniería de puertos y muelles","532 Construcción e ingeniería civil",608),
            new CamposProgramas("• Ingeniería de vías terrestres","532 Construcción e ingeniería civil",609),
            new CamposProgramas("• Ingeniería del abastecimiento de agua y alcantarillado","532 Construcción e ingeniería civil",610),
            new CamposProgramas("• Ingeniería estructural","532 Construcción e ingeniería civil",611),
            new CamposProgramas("• Ingeniería sanitaria","532 Construcción e ingeniería civil",612),
            new CamposProgramas("• Ingeniería y tecnología de la construcción","532 Construcción e ingeniería civil",613),
            new CamposProgramas("• Ingeniería y tecnología del agua","532 Construcción e ingeniería civil",614),
            new CamposProgramas("• Planeación de recursos hidráulicos","532 Construcción e ingeniería civil",615),
            new CamposProgramas("• Supervisión de obra","532 Construcción e ingeniería civil",616),
            new CamposProgramas("61 Agronomía, silvicultura y pesca",617),
            new CamposProgramas("611 Producción y explotación agrícola y ganadera",618),
            new CamposProgramas("• Agrología","611 Producción y explotación agrícola y ganadera",619),
            new CamposProgramas("• Ciencias agrícolas","611 Producción y explotación agrícola y ganadera",620),
            new CamposProgramas("• Ciencias biológico-agropecuarias","611 Producción y explotación agrícola y ganadera",621),
            new CamposProgramas("• Ciencias pecuarias","611 Producción y explotación agrícola y ganadera",622),
            new CamposProgramas("• Edafología","611 Producción y explotación agrícola y ganadera",623),
            new CamposProgramas("• Fisiopatología en agronomía","611 Producción y explotación agrícola y ganadera",624),
            new CamposProgramas("• Fitopatología","611 Producción y explotación agrícola y ganadera",625),
            new CamposProgramas("• Fitotecnia","611 Producción y explotación agrícola y ganadera",626),
            new CamposProgramas("• Ingeniería agrónoma","611 Producción y explotación agrícola y ganadera",627),
            new CamposProgramas("• Nutrición animal","611 Producción y explotación agrícola y ganadera",628),
            new CamposProgramas("• Sistemas de producción ganadera","611 Producción y explotación agrícola y ganadera",629),
            new CamposProgramas("• Zootecnia (apicultura, bovinocultura, ovinocultura, porcinocultura)","611 Producción y explotación agrícola y ganadera",630),
            new CamposProgramas("612 Horticultura",631),
            new CamposProgramas("• Agronomía en horticultura","612 Horticultura",632),
            new CamposProgramas("• Diseño de jardines","612 Horticultura",633),
            new CamposProgramas("• Floricultura","612 Horticultura",634),
            new CamposProgramas("• Horticultura","612 Horticultura",635),
            new CamposProgramas("• Olericultura","612 Horticultura",636),
            new CamposProgramas("• Protección vegetal de hortalizas","612 Horticultura",637),
            new CamposProgramas("613 Silvicultura",638),
            new CamposProgramas("• Dasonomía","613 Silvicultura",639),
            new CamposProgramas("• Desarrollo forestal","613 Silvicultura",640),
            new CamposProgramas("• Ingeniería y técnicas forestales","613 Silvicultura",641),
            new CamposProgramas("• Manejo de recursos forestales","613 Silvicultura",642),
            new CamposProgramas("• Mantenimiento de bosques","613 Silvicultura",643),
            new CamposProgramas("• Restauración forestal sustentable","613 Silvicultura",644),
            new CamposProgramas("• Sistemas forestales","613 Silvicultura",645),
            new CamposProgramas("614 Pesca",646),
            new CamposProgramas("• Acuicultura o acuacultura","614 Pesca",647),
            new CamposProgramas("• Ciencia y tecnología de la pesca","614 Pesca",648),
            new CamposProgramas("• Cultivos acuícolas","614 Pesca",649),
            new CamposProgramas("• Ingeniería acuícola","614 Pesca",650),
            new CamposProgramas("• Piscifactoría","614 Pesca",651),
            new CamposProgramas("62 Veterinaria",652),
            new CamposProgramas("621 Veterinaria",653),
            new CamposProgramas("• Asistencia veterinaria","621 Veterinaria",654),
            new CamposProgramas("• Atención de la salud animal","621 Veterinaria",655),
            new CamposProgramas("• Ciencias de la reproducción animal","621 Veterinaria",656),
            new CamposProgramas("• Enfermería veterinaria","621 Veterinaria",657),
            new CamposProgramas("• Fisiología comparada de animales domésticos","621 Veterinaria",658),
            new CamposProgramas("• Higiene veterinaria y salud pública","621 Veterinaria",659),
            new CamposProgramas("• Instrumentación, control y normas veterinarias","621 Veterinaria",660),
            new CamposProgramas("• Medicina veterinaria","621 Veterinaria",661),
            new CamposProgramas("• Reproducción animal","621 Veterinaria",662),
            new CamposProgramas("• Salud animal de grandes y pequeñas especies","621 Veterinaria",663),
            new CamposProgramas("71 Salud",664),
            new CamposProgramas("711 Medicina",665),
            new CamposProgramas("71101 Medicina general",666),
            new CamposProgramas("• Medicina general","711 Medicina",667),
            new CamposProgramas("• Medicina humana","711 Medicina",668),
            new CamposProgramas("• Médico cirujano","711 Medicina",669),
            new CamposProgramas("• Médico cirujano-partero","711 Medicina",670),
            new CamposProgramas("71102 Alergología e inmunología",671),
            new CamposProgramas("• Alergología clínica pediátrica","711 Medicina",672),
            new CamposProgramas("• Alergología e inmunología clínica","711 Medicina",673),
            new CamposProgramas("• Inmunología clínica","711 Medicina",674),
            new CamposProgramas("• Inmunoterapia","711 Medicina",675),
            new CamposProgramas("71103 Anestesiología",676),
            new CamposProgramas("• Algología","711 Medicina",677),
            new CamposProgramas("• Anestesiología pediátrica","711 Medicina",678),
            new CamposProgramas("• Neuroanestesiología","711 Medicina",679),
            new CamposProgramas("• Reanimación","711 Medicina",680),
            new CamposProgramas("71104 Angiología y cirugía vascular",681),
            new CamposProgramas("• Cirugía endovascular","711 Medicina",682),
            new CamposProgramas("• Flebología","711 Medicina",683),
            new CamposProgramas("• Sistema linfático","711 Medicina",684),
            new CamposProgramas("71105 Audiología",685),
            new CamposProgramas("• Audiología y patología del lenguaje","711 Medicina",686),
            new CamposProgramas("• Foniatría","711 Medicina",687),
            new CamposProgramas("• Medicina en audiología","711 Medicina",688),
            new CamposProgramas("• Otoneurología","711 Medicina",689),
            new CamposProgramas("71106 Cardiología",690),
            new CamposProgramas("• Cardiología clínica","711 Medicina",691),
            new CamposProgramas("• Cardiología nuclear","711 Medicina",692),
            new CamposProgramas("• Cardiología pediátrica","711 Medicina",693),
            new CamposProgramas("71107 Especialidad de cirugía general",694),
            new CamposProgramas("• Diagnóstico quirúrgico","711 Medicina",695),
            new CamposProgramas("• Progreso postoperatorio","711 Medicina",696),
            new CamposProgramas("• Procedimientos y técnicas quirúrgicas","711 Medicina",697),
            new CamposProgramas("71108 Cirugía de especialidad",698),
            new CamposProgramas("• Cirugía articular","711 Medicina",699),
            new CamposProgramas("• Cirugía bariátrica","711 Medicina",700),
            new CamposProgramas("• Cirugía cardiotorácica","711 Medicina",701),
            new CamposProgramas("• Cirugía de extremidades","711 Medicina",702),
            new CamposProgramas("• Cirugía de invasión de abdomen","711 Medicina",703),
            new CamposProgramas("• Cirugía endoscópica y laparoscópica","711 Medicina",704),
            new CamposProgramas("• Cirugía oncológica","711 Medicina",705),
            new CamposProgramas("• Cirugía pediátrica","711 Medicina",706),
            new CamposProgramas("• Cirugía plástica y reconstructiva","711 Medicina",707),
            new CamposProgramas("• Microcirugía","711 Medicina",708),
            new CamposProgramas("• Neurocirugía","711 Medicina",709),
            new CamposProgramas("• Neurocirugía pediátrica","711 Medicina",710),
            new CamposProgramas("71109 Dermatología",711),
            new CamposProgramas("• Dermatología pediátrica","711 Medicina",712),
            new CamposProgramas("• Dermopatología","711 Medicina",713),
            new CamposProgramas("• Venereología","711 Medicina",714),
            new CamposProgramas("71110 Endocrinología",715),
            new CamposProgramas("• Endocrinología pediátrica","711 Medicina",716),
            new CamposProgramas("71111 Endoscopía",717),
            new CamposProgramas("• Endoscopía diagnóstica y terapéutica","711 Medicina",718),
            new CamposProgramas("• Endoscopía digestiva","711 Medicina",719),
            new CamposProgramas("• Endoscopía gastrointestinal","711 Medicina",720),
            new CamposProgramas("71112 Gastroenterología",721),
            new CamposProgramas("• Gastroenterología pediátrica","711 Medicina",722),
            new CamposProgramas("• Gastroenterología y hepatología","711 Medicina",723),
            new CamposProgramas("71113 Genética médica",724),
            new CamposProgramas("• Citogenética clínica","711 Medicina",725),
            new CamposProgramas("• Genética extra nuclear","711 Medicina",726),
            new CamposProgramas("• Mutagénesis","711 Medicina",727),
            new CamposProgramas("71114 Geriatría",728),
            new CamposProgramas("• Geriatría","711 Medicina",729),
            new CamposProgramas("• Gerontología médica","711 Medicina",730),
            new CamposProgramas("71115 Ginecología y obstetricia",731),
            new CamposProgramas("• Alto riesgo obstétrico y ecografía","711 Medicina",732),
            new CamposProgramas("• Ginecología general","711 Medicina",733),
            new CamposProgramas("• Ginecología oncológica","711 Medicina",734),
            new CamposProgramas("• Ginecología oncológica y fisiopatología mamaria","711 Medicina",735),
            new CamposProgramas("• Medicina materno-fetal","711 Medicina",736),
            new CamposProgramas("• Medicina reproductiva","711 Medicina",737),
            new CamposProgramas("• Obstetricia general","711 Medicina",738),
            new CamposProgramas("• Perinatología","711 Medicina",739),
            new CamposProgramas("71116 Hematología",740),
            new CamposProgramas("• Hematología pediátrica","711 Medicina",741),
            new CamposProgramas("• Hemoterapia","711 Medicina",742),
            new CamposProgramas("• Inmunohematología","711 Medicina",743),
            new CamposProgramas("71117 Homeopatía y medicina de terapia complementaria",744),
            new CamposProgramas("• Medicina acupunturista","711 Medicina",745),
            new CamposProgramas("• Medicina de aromaterapia","711 Medicina",746),
            new CamposProgramas("• Medicina en iridiología","711 Medicina",747),
            new CamposProgramas("• Medicina tradicional china","711 Medicina",748),
            new CamposProgramas("71118 Infectología",749),
            new CamposProgramas("• Infectología clínica","711 Medicina",750),
            new CamposProgramas("• Infectología pediátrica","711 Medicina",751),
            new CamposProgramas("71119 Medicina interna y medicina de urgencias",752),
            new CamposProgramas("• Medicina del enfermo en estado crítico","711 Medicina",753),
            new CamposProgramas("• Medicina del enfermo pediátrico en estado crítico","711 Medicina",754),
            new CamposProgramas("71120 Medicina de la educación física y del deporte",755),
            new CamposProgramas("• Fisiología médico-deportiva","711 Medicina",756),
            new CamposProgramas("• Medicina de la actividad física","711 Medicina",757),
            new CamposProgramas("• Medicina del deporte","711 Medicina",758),
            new CamposProgramas("71121 Medicina del trabajo",759),
            new CamposProgramas("• Medicina del trabajo","711 Medicina",760),
            new CamposProgramas("• Medicina laboral","711 Medicina",761),
            new CamposProgramas("• Medicina ocupacional","711 Medicina",762),
            new CamposProgramas("71122 Medicina familiar",763),
            new CamposProgramas("• Salud de la familia","711 Medicina",764),
            new CamposProgramas("• Medicina comunitaria","711 Medicina",765),
            new CamposProgramas("71123 Medicina forense",766),
            new CamposProgramas("• Deontología profesional médica","711 Medicina",767),
            new CamposProgramas("• Medicina legal de la familia","711 Medicina",768),
            new CamposProgramas("• Medicina legal del trabajo","711 Medicina",769),
            new CamposProgramas("• Medicina legal o judicial","711 Medicina",770),
            new CamposProgramas("• Patología forense","711 Medicina",771),
            new CamposProgramas("71124 Nefrología",772),
            new CamposProgramas("• Nefrología clínica","711 Medicina",773),
            new CamposProgramas("• Nefrología pediátrica","711 Medicina",774),
            new CamposProgramas("71125 Neonatología y pediatría",775),
            new CamposProgramas("• Pediatría clínica","711 Medicina",776),
            new CamposProgramas("• Urgencias pediátricas","711 Medicina",777),
            new CamposProgramas("71126 Neumología",778),
            new CamposProgramas("• Neumología pediátrica","711 Medicina",779),
            new CamposProgramas("71127 Neurología",780),
            new CamposProgramas("• Neurocirugía","711 Medicina",781),
            new CamposProgramas("• Neurofisiología clínica","711 Medicina",782),
            new CamposProgramas("• Neurología pediátrica","711 Medicina",783),
            new CamposProgramas("• Terapia endovascular neurológica","711 Medicina",784),
            new CamposProgramas("71128 Oftalmología",785),
            new CamposProgramas("• Anatomía patológica ocular","711 Medicina",786),
            new CamposProgramas("• Fisiología-neurofisiología ocular","711 Medicina",787),
            new CamposProgramas("• Inmunología-bacteriología ocular","711 Medicina",788),
            new CamposProgramas("• Oftalmología neurológica","711 Medicina",789),
            new CamposProgramas("71129 Oncología médica",790),
            new CamposProgramas("• Oncología pediátrica","711 Medicina",791),
            new CamposProgramas("• Oncología radioterápica","711 Medicina",792),
            new CamposProgramas("71130 Otorrinolaringología",793),
            new CamposProgramas("• Neurootología","711 Medicina",794),
            new CamposProgramas("• Otorrinolaringología pediátrica","711 Medicina",795),
            new CamposProgramas("• Otorrinolaringología y cirugía de cabeza y cuello","711 Medicina",796),
            new CamposProgramas("71131 Patología y anatomía patológica",797),
            new CamposProgramas("• Histopatología","711 Medicina",798),
            new CamposProgramas("• Neuropatología","711 Medicina",799),
            new CamposProgramas("• Patología clínica","711 Medicina",800),
            new CamposProgramas("• Patología pediátrica","711 Medicina",801),
            new CamposProgramas("71132 Proctología",802),
            new CamposProgramas("• Coloproctología","711 Medicina",803),
            new CamposProgramas("71133 Psiquiatría",804),
            new CamposProgramas("• Psiquiatría hospitalaria y de la comunidad","711 Medicina",805),
            new CamposProgramas("• Psiquiatría infantil y de la adolescencia","711 Medicina",806),
            new CamposProgramas("• Salud mental comunitaria","711 Medicina",807),
            new CamposProgramas("• Trastornos del sueño","711 Medicina",808),
            new CamposProgramas("71134 Radiología",809),
            new CamposProgramas("• Medicina nuclear","711 Medicina",810),
            new CamposProgramas("• Radio oncología","711 Medicina",811),
            new CamposProgramas("• Radiodiagnóstico general y de áreas específicas","711 Medicina",812),
            new CamposProgramas("71135 Reumatología",813),
            new CamposProgramas("• Reumatología e inmunología clínica","711 Medicina",814),
            new CamposProgramas("• Reumatología pediátrica","711 Medicina",815),
            new CamposProgramas("71136 Traumatología y ortopedia",816),
            new CamposProgramas("• Artroscopía","711 Medicina",817),
            new CamposProgramas("• Cirugía de cadera y columna","711 Medicina",818),
            new CamposProgramas("• Cirugía ortopédica","711 Medicina",819),
            new CamposProgramas("• Fisiatría","711 Medicina",820),
            new CamposProgramas("• Traumatología y cirugía ortopédica","711 Medicina",821),
            new CamposProgramas("71137 Urología",822),
            new CamposProgramas("• Urología ginecológica","711 Medicina",823),
            new CamposProgramas("• Urología pediátrica","711 Medicina",824),
            new CamposProgramas("712 Enfermería y cuidados",825),
            new CamposProgramas("• Auxiliar/ ayudante/asistente de enfermería","712 Enfermería y cuidados",826),
            new CamposProgramas("• Ciencias de la enfermería","712 Enfermería y cuidados",827),
            new CamposProgramas("• Enfermería de cuidados intensivos","712 Enfermería y cuidados",828),
            new CamposProgramas("• Enfermería en psiquiatría","712 Enfermería y cuidados",829),
            new CamposProgramas("• Paramédicos","712 Enfermería y cuidados",830),
            new CamposProgramas("• Parteras o enfermería obstétrica","712 Enfermería y cuidados",831),
            new CamposProgramas("713 Estomatología y odontología",832),
            new CamposProgramas("• Ciencia dental","713 Estomatología y odontología",833),
            new CamposProgramas("• Cirugía dental","713 Estomatología y odontología",834),
            new CamposProgramas("• Enfermería dental","713 Estomatología y odontología",835),
            new CamposProgramas("• Metaendodoncia","713 Estomatología y odontología",836),
            new CamposProgramas("• Ortodoncia","713 Estomatología y odontología",837),
            new CamposProgramas("• Prostodoncia","713 Estomatología y odontología",838),
            new CamposProgramas("• Tecnología y prótesis dental","713 Estomatología y odontología",839),
            new CamposProgramas("714 Diagnóstico médico y tecnología del tratamiento",840),
            new CamposProgramas("• Análisis clínico","714 Diagnóstico médico y tecnología del tratamiento",841),
            new CamposProgramas("• Ingeniería biomédica","714 Diagnóstico médico y tecnología del tratamiento",842),
            new CamposProgramas("• Radiología e imagenología","714 Diagnóstico médico y tecnología del tratamiento",843),
            new CamposProgramas("• Radioterapia","714 Diagnóstico médico y tecnología del tratamiento",844),
            new CamposProgramas("• Resonancia magnética","714 Diagnóstico médico y tecnología del tratamiento",845),
            new CamposProgramas("• Tecnología auditiva","714 Diagnóstico médico y tecnología del tratamiento",846),
            new CamposProgramas("• Tecnología de laboratorio médico","714 Diagnóstico médico y tecnología del tratamiento",847),
            new CamposProgramas("• Tecnología de prótesis","714 Diagnóstico médico y tecnología del tratamiento",848),
            new CamposProgramas("• Tecnología de rayos X","714 Diagnóstico médico y tecnología del tratamiento",849),
            new CamposProgramas("• Tecnología óptica","714 Diagnóstico médico y tecnología del tratamiento",850),
            new CamposProgramas("715 Terapia y rehabilitación",851),
            new CamposProgramas("• Fisioterapia","715 Terapia y rehabilitación",852),
            new CamposProgramas("• Dietética","715 Terapia y rehabilitación",853),
            new CamposProgramas("• Logopedia","715 Terapia y rehabilitación",854),
            new CamposProgramas("• Nutrición","715 Terapia y rehabilitación",855),
            new CamposProgramas("• Optometría","715 Terapia y rehabilitación",856),
            new CamposProgramas("• Osteopatía","715 Terapia y rehabilitación",857),
            new CamposProgramas("• Quiropráctica","715 Terapia y rehabilitación",858),
            new CamposProgramas("• Terapia de la patología del habla","715 Terapia y rehabilitación",859),
            new CamposProgramas("• Terapia de masaje y rehabilitación","715 Terapia y rehabilitación",860),
            new CamposProgramas("• Terapia ocupacional","715 Terapia y rehabilitación",861),
            new CamposProgramas("716 Farmacia",862),
            new CamposProgramas("• Biofarmacia","716 Farmacia",863),
            new CamposProgramas("• Control de medicamentos","716 Farmacia",864),
            new CamposProgramas("• Desarrollo farmacéutico","716 Farmacia",865),
            new CamposProgramas("• Distribución farmacéutica","716 Farmacia",866),
            new CamposProgramas("717 Salud pública",867),
            new CamposProgramas("• Atención a la salud","717 Salud pública",868),
            new CamposProgramas("• Epidemiología humana","717 Salud pública",869),
            new CamposProgramas("• Salud ambiental","717 Salud pública",870),
            new CamposProgramas("• Salud comunitaria","717 Salud pública",871),
            new CamposProgramas("• Salud en el trabajo","717 Salud pública",872),
            new CamposProgramas("• Salud ocupacional","717 Salud pública",873),
            new CamposProgramas("• Sistemas de salud","717 Salud pública",874),
            new CamposProgramas("710 Salud, programas multidisciplinarios o generales",875),
            new CamposProgramas("• Ciencias de la salud","710 Salud, programas multidisciplinarios o generales",876),
            new CamposProgramas("• Investigación clínica en salud","710 Salud, programas multidisciplinarios o generales",877),
            new CamposProgramas("• Investigación en salud","710 Salud, programas multidisciplinarios o generales",878),
            new CamposProgramas("81 Servicios personales",879),
            new CamposProgramas("811 Deportes",880),
            new CamposProgramas("• Ciencias del deporte","811 Deportes",881),
            new CamposProgramas("• Ciencias del ejercicio","811 Deportes",882),
            new CamposProgramas("• Cultura física","811 Deportes",883),
            new CamposProgramas("• Deporte en disciplinas de atletismo","811 Deportes",884),
            new CamposProgramas("• Deporte en disciplinas de bádminton","811 Deportes",885),
            new CamposProgramas("• Deporte en disciplinas de boliche","811 Deportes",886),
            new CamposProgramas("• Deporte en disciplinas de ciclismo","811 Deportes",887),
            new CamposProgramas("• Entrenador de fútbol","811 Deportes",888),
            new CamposProgramas("• Práctica del ciclismo","811 Deportes",889),
            new CamposProgramas("• Preparador físico de fútbol","811 Deportes",890),
            new CamposProgramas("812 Servicios de embalsamamiento",891),
            new CamposProgramas("• Embalsamamiento","812 Servicios de embalsamamiento",892),
            new CamposProgramas("• Histopatólogo-embalsamador","812 Servicios de embalsamamiento",893),
            new CamposProgramas("813 Servicios de belleza",894),
            new CamposProgramas("• Calicultura","813 Servicios de belleza",895),
            new CamposProgramas("• Cosmeatría","813 Servicios de belleza",896),
            new CamposProgramas("• Cosmetología","813 Servicios de belleza",897),
            new CamposProgramas("• Esteticismo","813 Servicios de belleza",898),
            new CamposProgramas("• Estilismo","813 Servicios de belleza",899),
            new CamposProgramas("814 Secretariado y asistencia administrativa",900),
            new CamposProgramas("• Asistencia ejecutiva","814 Secretariado y asistencia administrativa",901),
            new CamposProgramas("• Asistencia en aspectos contables","814 Secretariado y asistencia administrativa",902),
            new CamposProgramas("• Asistente en administración","814 Secretariado y asistencia administrativa",903),
            new CamposProgramas("• Secretariado contable","814 Secretariado y asistencia administrativa",904),
            new CamposProgramas("• Secretariado ejecutivo","814 Secretariado y asistencia administrativa",905),
            new CamposProgramas("• Secretariado en lenguas extranjeras","814 Secretariado y asistencia administrativa",906),
            new CamposProgramas("• Secretariado informático","814 Secretariado y asistencia administrativa",907),
            new CamposProgramas("82 Servicios de transporte",908),
            new CamposProgramas("821 Servicios de transporte",909),
            new CamposProgramas("• Estructuras del transporte","821 Servicios de transporte",910),
            new CamposProgramas("• Formación de pilotos (navales o aviadores)","821 Servicios de transporte",911),
            new CamposProgramas("• Logística de transporte","821 Servicios de transporte",912),
            new CamposProgramas("• Maquinista","821 Servicios de transporte",913),
            new CamposProgramas("• Sistemas de transporte urbano","821 Servicios de transporte",914),
            new CamposProgramas("• Tránsito y transportes","821 Servicios de transporte",915),
            new CamposProgramas("• Transporte público terrestre, aéreo o marítimo","821 Servicios de transporte",916),
            new CamposProgramas("• Transporte y distribución de carga","821 Servicios de transporte",917),
            new CamposProgramas("83 Seguridad industrial",918),
            new CamposProgramas("831 Seguridad industrial",919),
            new CamposProgramas("• Mantenimiento y seguridad industrial","831 Seguridad industrial",920),
            new CamposProgramas("• Seguridad e higiene industrial","831 Seguridad industrial",921),
            new CamposProgramas("• Seguridad en el trabajo","831 Seguridad industrial",922),
            new CamposProgramas("• Seguridad ocupacional","831 Seguridad industrial",923),
            new CamposProgramas("84 Servicios de seguridad",924),
            new CamposProgramas("841 Seguridad pública",925),
            new CamposProgramas("• Ciencias policiales","841 Seguridad pública",926),
            new CamposProgramas("• Investigación policial","841 Seguridad pública",927),
            new CamposProgramas("• Policía ministerial","841 Seguridad pública",928),
            new CamposProgramas("• Policía preventiva","841 Seguridad pública",929),
            new CamposProgramas("• Protección Civil","841 Seguridad pública",930),
            new CamposProgramas("• Seguridad","841 Seguridad pública",931),
            new CamposProgramas("• Seguridad ciudadana","841 Seguridad pública",932),
            new CamposProgramas("842 Servicios militares",933),
            new CamposProgramas("• Armamento aéreo","842 Servicios militares",934),
            new CamposProgramas("• Ciencias militares","842 Servicios militares",935),
            new CamposProgramas("• Materiales de guerra","842 Servicios militares",936),
            new CamposProgramas("• Sistemas de armas","842 Servicios militares",937)
    };

    public CamposProgramas(String nombre, int id) {
        this.nombre = nombre;
        this.id = id;
    }

    public CamposProgramas(String nombre, String campoDetallado, int id) {
        this.nombre = nombre;
        this.campoDetallado = campoDetallado;
        this.id = id;
    }

    public static CamposProgramas[] getCamposProgramas() {
        return camposProgramas;
    }

    public static CamposProgramas[] getCamposProgramasEducación() {
        return Arrays.copyOfRange(camposProgramas, 0, 78) ;
    }

    public static CamposProgramas[] getCamposProgramasArtesHumanidades() {
        return Arrays.copyOfRange(camposProgramas, 78, 164);
    }

    public static CamposProgramas[] getCamposProgramasCienciasSocialesAdministraciónDerecho() {
        return Arrays.copyOfRange(camposProgramas, 164, 364);
    }

    public static CamposProgramas[] getCamposProgramasCienciasNaturalesExactasComputación() {
        return Arrays.copyOfRange(camposProgramas, 364, 456);
    }

    public static CamposProgramas[] getCamposProgramasIngenieríaManufacturaConstrucción() {
        return Arrays.copyOfRange(camposProgramas, 456, 617);
    }

    public static CamposProgramas[] getCamposProgramasAgronomíaVeterinaria() {
        return Arrays.copyOfRange(camposProgramas, 617, 664);
    }

    public static CamposProgramas[] getCamposProgramasSalud() {
        return Arrays.copyOfRange(camposProgramas, 664, 879);
    }

    public static CamposProgramas[] getCamposProgramasServicios() {
        return Arrays.copyOfRange(camposProgramas, 879, 938);
    }

    public String getNombre() {
        return nombre;
    }

    public String getCampoDetallado() {
        return campoDetallado;
    }

    public String getCampoDetalladoNombre() {
        return campoDetallado.substring(4);
    }

    public int getCampoDetalladoClave() {
        return Integer.valueOf(campoDetallado.substring(0, 3));
    }

    public int getId() {
        return id;
    }

    public static ArrayList<CamposProgramas> getProgramas() {
        ArrayList<CamposProgramas> programas = new ArrayList<CamposProgramas>();
        for (CamposProgramas item: camposProgramas) {
            Pattern p = Pattern.compile("^•\\s");
            Matcher m = p.matcher(item.getNombre());
            if (m.find()) {
                programas.add(item);
            }
        }
        return programas;
    }

    public static ArrayList<CamposProgramas> filtrarProgramas(String nombrePrograma) { //Compara la cadena recibida con cada uno de los nombres que estén en programas y devuelve los que coincidan.
        ArrayList<CamposProgramas> listaFiltrada = new ArrayList<CamposProgramas>();
        for(CamposProgramas item: getProgramas()) {
            if(item.getNombre().toLowerCase().contains(nombrePrograma)) {
                listaFiltrada.add(item);
            }
        }
        return listaFiltrada;
    }

    public static ArrayList<CamposProgramas> getProgramasFavoritos(Map<String, ?> favoritos) {
        ArrayList<CamposProgramas> programasFavoritos = new ArrayList<CamposProgramas>();

        for(Map.Entry<String,?> entry : favoritos.entrySet()){
            int posición = Integer.valueOf(String.valueOf(entry.getValue()));

            programasFavoritos.add(getCamposProgramas()[posición]);
        }

        return programasFavoritos;
    }

    protected CamposProgramas(Parcel in) {
        nombre = in.readString();
        campoDetallado = in.readString();
        id = in.readInt();
    }

    public static final Creator<CamposProgramas> CREATOR = new Creator<CamposProgramas>() {
        @Override
        public CamposProgramas createFromParcel(Parcel in) {
            return new CamposProgramas(in);
        }

        @Override
        public CamposProgramas[] newArray(int size) {
            return new CamposProgramas[size];
        }
    };

    @Override
    public int describeContents() {
        return 0;
    }

    @Override
    public void writeToParcel(Parcel dest, int flags) {
        dest.writeString(nombre);
        dest.writeString(campoDetallado);
        dest.writeInt(id);
    }
}